# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{next-big-sound}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["jeff durand"]
  s.date = %q{2010-03-29}
  s.description = %q{A simple wrapper class for the Next Big Sound api.  docs for the api can be found at api.nextbigsound.com}
  s.email = %q{jeff.durand@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/artist.rb",
     "lib/artist_profile.rb",
     "lib/config.yml",
     "lib/datapoint.rb",
     "lib/hash_extension.rb",
     "lib/metric.rb",
     "lib/next-big-sound.rb",
     "lib/search.rb",
     "next-big-sound.gemspec",
     "test/helper.rb",
     "test/test_search.rb"
  ]
  s.homepage = %q{http://github.com/johnnyiller/next-big-sound}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Next Big Sound}
  s.test_files = [
    "test/helper.rb",
     "test/test_search.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

